apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sika-training-examples/2024-10-18_integritty-charts.git
      path: ./integritty-php
      helm:
        valueFiles:
          - $values/apps/sikademo/example/example.values.yml
          - $values/apps/sikademo/example/example.image.values.yml
    - repoURL: https://gitlab.sikalabs.com/examples/integritty/argocd-apps.git
      ref: values
